#!/bin/bash

set -eou pipefail

if [ $# -ne 0 ]; then
    echo "Usage: git create-pr"
    exit -1
fi

token=undefined

function create_pr {
    local remote="$1"
    local branch="$2"

    local origin_api_path=$(git config --get remote.origin.url | sed 's/.*:\(.*\).git/\1/')
    local remote_api_path=$(git config --get remote.$remote.url | sed 's/.*:\(.*\).git/\1/')
    local remote_user=$(echo $remote_api_path | sed 's,/.*,,')
    local remote_head="$remote_user:$branch"
    local remote_host=$(git config --get hub.host)
    local api_url="https://$remote_host/api/v3/repos/$origin_api_path/pulls"

    local title=$(git log -n 1 --format=format:%s | sed 's/"/\\"/g')

    set +e
    local response=$(curl -s -H "Authorization: token $token" "$api_url" -d "{ \
        \"title\": \"$title\", \
        \"head\": \"$remote_head\", \
        \"base\": \"master\" \
    }")
    local status=$?
    set -e
    if [ $? -ne 0 ]; then
        echo "PR creation failed! Output: "
        echo "$response"
    fi

    local pr_number="$(extract_json "$response" "number")"
    echo -n "PR $pr_number created! Open in a browser? [Y/n] "
    read open_pr
    if [ -z "$open_pr" ] || [ "$open_pr" == "Y" ] || [ "$open_pr" == "y" ]; then
        local pr_url="$(extract_json "$response" "html_url" | tr -d '"')"
        open $pr_url
    fi
}

function extract_json {
    echo "$1" | grep "^  \"$2\": " | sed 's/.*: \(.*\),.*/\1/'
}

function main {
    set +e
    token=$(git config --get prtools.token)
    if [ $? -ne 0 ]; then
        echo "A GitHub token must be provided. Generate one on GitHub:"
        echo "    https://github.com/settings/tokens/new"
        echo
        echo "The token needs to have the 'repo' scope (or probably some"
        echo "subset of it)."
        echo ""
        echo "Then, add it to your git config: "
        echo "    git config --global --add prtools.token <github-token>"
        exit -1
    fi
    set -e

    local head_sha=$(git reflog -n 1 --format=format:%H)

    set +e
    local remotes="$(git remote | grep -v origin)"
    if [ $? -ne 0 ]; then
        if [ $(git remote | grep -c origin) -eq 0 ]; then
            echo "Coudn't find any remotes. Is this git repo configured yet?"
        else
            echo "Couldn't find any remotes other than origin. Perhaps you"
            echo "should create a fork? You can do this with the 'hub' CLI tool:"
            echo "    hub fork"
        fi
        exit -1
    fi
    set -e

    local created=false
    for remote in $(git remote | grep -v origin); do
        local candidate_sha=$(git ls-remote --heads $remote | grep "$head_sha")
        if [ -n "$candidate_sha" ]; then
            local candidate_branch=$(echo "$candidate_sha" | awk '{print $2}' | sed 's,refs/heads/,,')
            create_pr "$remote" "$candidate_branch"
            created=true
            break
        fi
    done

    if ! $created; then
        echo "No local changes found to create PRs for!"
        exit -1
    fi
}

main
